### ISSUE TITLE
2 typo

### ISSUE THREAD

**Issue by antoniocerullo** [paoloscapin/GestOre#37]
Segnalo due piccoli typo:

https://github.com/paoloscapin/GestOre/blob/master/admin/utenteReadRecords.php?plain=1#L17 

Nome<ins>e</ins>

https://github.com/paoloscapin/GestOre/blob/master/dirigente/filtroPrevisteReadRecords.php?plain=1#L73

To<ins>r</ins>ale

**Comment by paoloscapin** [comment]
fixed
Version 1.2.47 - 7 ago 2024
